# Generated by Django 5.2.11 on 2026-04-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
